# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Umbrella_dep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='sub_department',
            name='umbrella_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umbrella.Umbrella_dep'),
        ),
        migrations.AddField(
            model_name='d_employee',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umbrella.Sub_department'),
        ),
    ]
