# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-31 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0002_sub_department_technology1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_department',
            old_name='technology1',
            new_name='technology',
        ),
    ]
